### ISSUE TITLE
Reset Button Adjustment

### ISSUE THREAD

**Issue by angelleye** [angelleye/wp-paypal-marketing-solutions#12]
We need to find a better place for the reset button:

![image](https://user-images.githubusercontent.com/629241/33336130-9f79417c-d434-11e7-9236-43b747ac0a09.png)

**Comment by kcppdevelopers** [comment]
@angelleye should I move it to below '* As reported in Nielsen’s PayPal Credit Average' text or 'PayPal Marketing Solutions' title ? Could you please suggest better place?

**Comment by angelleye** [comment]
@kcppdevelopers  Maybe we could do an additional tab called Tools and just put that button there for now?

**Comment by angelleye** [comment]
@kcppdevelopers Or, maybe we can remove the button entirely and simply tie the reset / clear CID into the Uninstall of the plugin..??  So if somebody wants to clear it out and start fresh they would just have to uninstall the plugin (not just deactivate, but uninstall) and then re-install.  Will that work?

**Comment by angelleye** [comment]
@kcppdevelopers I think I'd like to go ahead and to the extra Tools tab and move the button inside there.  Also, when the Reset button is pushed we need a dialog to explain what's happening with option to Proceed or Cancel.

**Comment by angelleye** [comment]
@kcppdevelopers Now that I think about it more, we should be clearing out the CID on uninstall even with our button to reset in its own tab.  Did you do that already, or can you get that done for me please?
