### ISSUE TITLE
Add Analytics Tags

### ISSUE THREAD

**Issue by angelleye** [angelleye/wp-paypal-marketing-solutions#15]
Looks like we're missing some fields in the request that we need to add, highlighted in green:

![image](https://user-images.githubusercontent.com/629241/33349752-1da7b5ca-d461-11e7-8369-ddb1284f599d.png)

**Comment by kcppdevelopers** [comment]
@angelleye we have only used JS version, so above API request parameters not used.

**Comment by angelleye** [comment]
Ok, I'll close the issue for now and see if they bring it up when we deliver this.
