### ISSUE TITLE
PayPal Rep Feedback

### ISSUE THREAD

**Issue by angelleye** [angelleye/wp-paypal-marketing-solutions#16]
* https://mail.google.com/mail/u/0/#inbox/1600a97eba6d4a18

> Looks very good. With stand-alone using JS integration for activation, the T&Cs part of the in-context PP page (highlighted 1st screen shot below); therefore, please remove the T&Cs from your page in this stand-alone plugin (highlighted 2nd screen shot below).
> 
> Also, to confirm, from prior email (excerpt below), if WooCommerce is enabled and active on the site, its’ also added to WooCommerce -> Settings -> Checkout Tab ? And has to two specific setup guides for WP & Woo?

> ·        Create "PayPal Insights" (or whatever the verbiage ends up being) for WordPress.
> o   Install / Setup Guide we will create for it that instructs people on how to install and configure the plugin quickly and easily.
> o   The default location for this plugin's settings will be under WP Settings -> PayPal Insights.
> §  If WooCommerce is enabled and active on the site, we will also add PayPal Insights Settings into the WooCommerce -> Settings -> Checkout Tab so that it's accessible directly inside the WooCommerce system as well as under the general WP settings.
> ·        We can put together a Woo specific setup guide so that when you link from your setup wizard site it will be targeted at WooCommerce.
> ·        A separate guide specific to WP in general can be used if you want to update your wizard to also include that as an option separate from Woo.

> ![image](https://user-images.githubusercontent.com/629241/33584262-2b0e4e78-d924-11e7-9e69-5629acd99c96.png)
> 
> ![image](https://user-images.githubusercontent.com/629241/33584263-2e7056ec-d924-11e7-8a6b-990a001bb355.png)

**Comment by kcppdevelopers** [comment]
@angelleye  I have remove T&Cs part and changed setting location, now setting location available under Settings -> PayPal Marketing Solutions.

**Comment by angelleye** [comment]
@kcppdevelopers Do we also have it under WooCommerce -> Settings -> Checkout?

**Comment by kcppdevelopers** [comment]
@angelleye No, we also have it under WooCommerce -> Settings -> PayPal Marketing Solutions

**Comment by angelleye** [comment]
@kcppdevelopers Okay, I see we have it under WooCommerce -> Settings as its own tab, so that's good.  

I see you moved it from the primary menu bar into Settings -> PayPal Marketing Solutions because of that last comment.  We may actually move that back to the primary menu, though.  I think he liked it better there so I am clarifying.  Waiting on confirmation...

**Comment by angelleye** [comment]
@kcppdevelopers PayPal has a video for this now:  https://youtu.be/hXWFn8_jUDc

Please replace our More Info graphic with that video, and make sure the pop-up window size matches nicely with the video and looks good.

**Comment by kcppdevelopers** [comment]
@angelleye I have added video URL and push to dev branch.
