### ISSUE TITLE
Partner Code

### ISSUE THREAD

**Issue by angelleye** [angelleye/wp-paypal-marketing-solutions#5]
Need to do our standard routine for ensuring our partner code gets included with PayPal payments.  This includes looking for WC and overriding their code with our own as well as our JS that searches for PayPal buttons on any page and injects/overrides BN with our value.

**Comment by angelleye** [comment]
We should look to do this for Woo Express, Payments Pro, and Braintree if we can.

**Comment by angelleye** [comment]
Not sure if the above commit is correct or not.  I think it would work, but should it go in `/includes/class-wp-paypal-insights.php` instead?

**Comment by angelleye** [comment]
@kcppdevelopers Can you clarify what you did in the above commit?  Not sure how most of that relates to this issue..??  Also just curious about the changes you made in general..??

**Comment by kcppdevelopers** [comment]
@angelleye I have remove extra code, remove file and folder and change few code.

**Comment by angelleye** [comment]
@kcppdevelopers Can you elaborate on that a little bit please?  I generated the boilerplate structure from https://wppb.me/.  What is it including that is "extra"?

**Comment by angelleye** [comment]
@kcppdevelopers We missed what we were supposed to do in this issue.

 - Use the WC hook to override their BN code in PayPal standard with ours:  AngellEYE_SP_BM_WordPress
 - Add our JS that searches for PayPal standard buttons in page/post content and injects our BN code where it finds buttons.
 - Check to see if Woo Braintree is being used, and if so, see if we can override their BN code with ours.
 - Check to see if Woo Express Checkout is being used, and if so, see if we can override.
 - Check to see if Woo PayPal Pro is being used, and if so, see if we can override.

**Comment by angelleye** [comment]
Holding off on this because I think PayPal will own this code instead of us releasing it under Angell EYE.
